[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clock-overlay"
version = "v1.1.0"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3"
]

[project.scripts]
clock-overlay = "clockoverlay.__main__:main"
